name: kurilki
description: Glory to Ukraine.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.1.0"


dependencies:
  flutter:
    sdk: flutter

  #DI
  get_it: ^7.2.0
  injectable: ^1.5.3
  equatable: ^2.0.3


  #SM
  rxdart: ^0.27.3
  flutter_bloc: ^8.0.1


  #REST
  dio: ^4.0.4
  retrofit: ^3.0.1+1
  uuid: ^3.0.4



  #UTILITY
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  internet_connection_checker: ^0.0.1+2
  connectivity_plus: ^2.2.0
  auto_route: ^4.2.1


  #DESIGN
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.3.1
  flutter_expanded_tile: ^0.3.6
  another_flushbar: ^1.10.28
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  lottie: ^1.3.0
  flutter_slidable: ^1.3.0

  group_radio_button: ^1.2.0






  #OTHER
  logger: ^1.1.0
  json_annotation: ^4.4.0
  easy_localization: ^3.0.0

  #DATA
  shared_preferences: ^2.0.15


  #FIREBASE
  firebase_core: ^1.11.0
  google_sign_in: ^5.1.0
  firebase_auth: ^3.3.14
  firebase_analytics: ^9.1.3
  firebase_app_check: ^0.0.6+8
  firebase_crashlytics: ^2.6.1
  cloud_firestore: ^3.4.0



dev_dependencies:
  flutter_native_splash: ^2.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4

  #codegen
  build_runner: ^2.1.11
  auto_route_generator: ^4.2.0
  injectable_generator: ^1.3.3
  json_serializable: ^6.2.0



flutter_test:
  sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
    - assets/translations/

flutter_native_splash:
  color: "#F5F5F5"
  image: assets/icons/logo.png
  color_dark: "#F5F5F5"
  image_dark: assets/icons/logo.png
  android_12:
    color: "#F5F5F5"
    image: assets/icons/logo.png
    image_dark: assets/icons/logo.png
    icon_background_color: "F5F5F5"
    icon_background_color_dark: "#F5F5F5"

  ios_content_mode: center